
(()=>{"use strict";
const C={H:"#e5e7eb",O:"#e53935",Mg:"#aab3bf",Zn:"#687585",Cl:"#35a854",Ag:"#d5dde6",Na:"#8359d8",C:"#263238",N:"#3977d8",Fe:"#6b7280",S:"#eab308",Ca:"#94a3b8",K:"#8b5cf6",Br:"#9a3412",Pb:"#6b7280",I:"#7c3aed",Ba:"#a8a29e",Cu:"#b45309"};
const DATA={
mg:{name:"Magnesium reacting with oxygen",type:"synthesis",reactants:["magnesium","oxygen"],products:["magnesium oxide"],f:["Mg","O₂","MgO"],side:["r","r","p"],coef:[2,1,2],eq:"2Mg + O₂ → 2MgO",desc:"Magnesium and oxygen combine to form magnesium oxide. A brilliant white light and a large temperature increase provide visible evidence.",obs:["light production","temperature increase","colour change"],t:[22,180],ph:null,gas:"None",ppt:"None",lab:"burn",atoms:[["Mg"],["Mg"],["O","O"]],groups:[[0,2],[1,3]],elements:["Mg","Mg","O","O"],hint:"Two reactants combine to form one compound."},
per:{name:"Hydrogen peroxide decomposition",type:"decomposition",reactants:["hydrogen peroxide"],products:["water","oxygen"],f:["H₂O₂","H₂O","O₂"],side:["r","p","p"],coef:[2,2,1],eq:"2H₂O₂ → 2H₂O + O₂",desc:"Hydrogen peroxide decomposes into water and oxygen. Bubbles show oxygen gas being produced.",obs:["gas formation","temperature increase"],t:[22,27],ph:[5,5.5],gas:"Oxygen",ppt:"None",lab:"bubble",atoms:[["H","O","O","H"],["H","O","O","H"]],groups:[[0,1,3],[4,5,7],[2,6]],elements:["H","O","O","H","H","O","O","H"],hint:"One compound forms two simpler products."},
zn:{name:"Zinc reacting with hydrochloric acid",type:"single displacement",reactants:["zinc","hydrochloric acid"],products:["zinc chloride","hydrogen"],f:["Zn","HCl","ZnCl₂","H₂"],side:["r","r","p","p"],coef:[1,2,1,1],eq:"Zn + 2HCl → ZnCl₂ + H₂",desc:"Zinc displaces hydrogen from hydrochloric acid. Zinc dissolves and hydrogen bubbles form.",obs:["gas formation","temperature increase","solid dissolves"],t:[22,31],ph:[1,2],gas:"Hydrogen",ppt:"None",lab:"metal",atoms:[["Zn"],["H","Cl"],["H","Cl"]],groups:[[0,2,4],[1,3]],elements:["Zn","H","Cl","H","Cl"],hint:"One element replaces another in a compound."},
ag:{name:"Silver nitrate reacting with sodium chloride",type:"double displacement",reactants:["silver nitrate","sodium chloride"],products:["silver chloride","sodium nitrate"],f:["AgNO₃","NaCl","AgCl","NaNO₃"],side:["r","r","p","p"],coef:[1,1,1,1],eq:"AgNO₃ + NaCl → AgCl + NaNO₃",desc:"Dissolved ions exchange partners. Insoluble silver chloride appears as a white precipitate.",obs:["precipitate formation","colour change"],t:[22,22],ph:[7,7],gas:"None",ppt:"Silver chloride",lab:"ppt",atoms:[["Ag","N","O","O","O"],["Na","Cl"]],groups:[[0,6],[5,1,2,3,4]],elements:["Ag","N","O","O","O","Na","Cl"],hint:"Two ionic compounds exchange ions and form an insoluble product."},
ch4:{name:"Methane combustion",type:"combustion",reactants:["methane","oxygen"],products:["carbon dioxide","water"],f:["CH₄","O₂","CO₂","H₂O"],side:["r","r","p","p"],coef:[1,2,1,2],eq:"CH₄ + 2O₂ → CO₂ + 2H₂O",desc:"Methane reacts with oxygen and releases heat and light. Complete combustion forms carbon dioxide and water.",obs:["light production","temperature increase","gas formation"],t:[22,240],ph:null,gas:"Carbon dioxide and water vapour",ppt:"None",lab:"flame",atoms:[["H","H","C","H","H"],["O","O"],["O","O"]],groups:[[5,2,7],[0,6,1],[3,8,4]],elements:["H","H","C","H","H","O","O","O","O"],hint:"A hydrocarbon reacts with oxygen and releases energy."},
neut:{name:"Hydrochloric acid reacting with sodium hydroxide",type:"acid–base neutralisation",reactants:["hydrochloric acid","sodium hydroxide"],products:["sodium chloride","water"],f:["HCl","NaOH","NaCl","H₂O"],side:["r","r","p","p"],coef:[1,1,1,1],eq:"HCl + NaOH → NaCl + H₂O",desc:"An acid and a base react to form salt and water. The pH moves towards neutral and the mixture warms.",obs:["temperature increase","pH change"],t:[22,29],ph:[1,7],gas:"None",ppt:"None",lab:"neutral",atoms:[["H","Cl"],["Na","O","H"]],groups:[[2,1],[0,3,4]],elements:["H","Cl","Na","O","H"],hint:"An acid and base form salt and water."},
feS:{name:"Iron reacting with sulfur",type:"synthesis",reactants:["iron","sulfur"],products:["iron sulfide"],f:["Fe","S","FeS"],side:["r","r","p"],coef:[1,1,1],eq:"Fe + S → FeS",desc:"Iron and sulfur combine on heating to form iron sulfide. The mixture glows and forms a dark solid.",obs:["light production","temperature increase","colour change"],t:[22,120],ph:null,gas:"None",ppt:"None",lab:"burn",atoms:[["Fe"],["S"]],groups:[[0,1]],elements:["Fe","S"],hint:"Two elements combine to form one compound."},
caCO3:{name:"Calcium carbonate thermal decomposition",type:"decomposition",reactants:["calcium carbonate"],products:["calcium oxide","carbon dioxide"],f:["CaCO₃","CaO","CO₂"],side:["r","p","p"],coef:[1,1,1],eq:"CaCO₃ → CaO + CO₂",desc:"Heating calcium carbonate produces calcium oxide and carbon dioxide gas.",obs:["gas formation","temperature increase","colour change"],t:[22,180],ph:null,gas:"Carbon dioxide",ppt:"None",lab:"bubble",atoms:[["Ca","C","O","O","O"]],groups:[[0,2],[3,1,4]],elements:["Ca","C","O","O","O"],hint:"One compound breaks into two simpler substances."},
naHCO3:{name:"Sodium hydrogencarbonate decomposition",type:"decomposition",reactants:["sodium hydrogencarbonate"],products:["sodium carbonate","carbon dioxide","water"],f:["NaHCO₃","Na₂CO₃","CO₂","H₂O"],side:["r","p","p","p"],coef:[2,1,1,1],eq:"2NaHCO₃ → Na₂CO₃ + CO₂ + H₂O",desc:"On heating, sodium hydrogencarbonate decomposes to sodium carbonate, carbon dioxide and water vapour.",obs:["gas formation","temperature increase"],t:[22,110],ph:null,gas:"Carbon dioxide and water vapour",ppt:"None",lab:"bubble",atoms:[["Na","H","C","O","O","O"],["Na","H","C","O","O","O"]],groups:[[0,6,2,3,4],[8,1,9],[5,7,10]],elements:["Na","H","C","O","O","O","Na","H","C","O","O","O"],hint:"A single reactant forms several products."},
feCu:{name:"Iron reacting with copper sulfate",type:"single displacement",reactants:["iron","copper sulfate"],products:["iron(II) sulfate","copper"],f:["Fe","CuSO₄","FeSO₄","Cu"],side:["r","r","p","p"],coef:[1,1,1,1],eq:"Fe + CuSO₄ → FeSO₄ + Cu",desc:"Iron displaces copper from copper sulfate. The blue solution fades and reddish-brown copper forms.",obs:["colour change","solid formation","temperature increase"],t:[22,27],ph:[4,4],gas:"None",ppt:"Copper forms on the metal",lab:"metal",atoms:[["Fe"],["Cu","S","O","O","O","O"]],groups:[[0,2,3,4,5,6],[1]],elements:["Fe","Cu","S","O","O","O","O"],hint:"A more reactive metal replaces a less reactive metal."},
clKBr:{name:"Chlorine reacting with potassium bromide",type:"single displacement",reactants:["chlorine","potassium bromide"],products:["potassium chloride","bromine"],f:["Cl₂","KBr","KCl","Br₂"],side:["r","r","p","p"],coef:[1,2,2,1],eq:"Cl₂ + 2KBr → 2KCl + Br₂",desc:"Chlorine displaces bromine from potassium bromide. The solution develops an orange-brown colour.",obs:["colour change"],t:[22,22],ph:[7,7],gas:"None",ppt:"None",lab:"neutral",atoms:[["Cl","Cl"],["K","Br"],["K","Br"]],groups:[[2,0],[4,1],[3,5]],elements:["Cl","Cl","K","Br","K","Br"],hint:"A more reactive halogen replaces a less reactive halogen."},
pbKI:{name:"Lead nitrate reacting with potassium iodide",type:"double displacement",reactants:["lead nitrate","potassium iodide"],products:["lead iodide","potassium nitrate"],f:["Pb(NO₃)₂","KI","PbI₂","KNO₃"],side:["r","r","p","p"],coef:[1,2,1,2],eq:"Pb(NO₃)₂ + 2KI → PbI₂ + 2KNO₃",desc:"Ions exchange partners and bright yellow lead iodide precipitates.",obs:["precipitate formation","colour change"],t:[22,22],ph:[7,7],gas:"None",ppt:"Lead iodide",lab:"ppt",atoms:[["Pb","N","O","O","O","N","O","O","O"],["K","I"],["K","I"]],groups:[[0,10,12],[9,1,2,3,4],[11,5,6,7,8]],elements:["Pb","N","O","O","O","N","O","O","O","K","I","K","I"],hint:"Two ionic compounds exchange partners and form a yellow solid."},
baSO4:{name:"Barium chloride reacting with sodium sulfate",type:"double displacement",reactants:["barium chloride","sodium sulfate"],products:["barium sulfate","sodium chloride"],f:["BaCl₂","Na₂SO₄","BaSO₄","NaCl"],side:["r","r","p","p"],coef:[1,1,1,2],eq:"BaCl₂ + Na₂SO₄ → BaSO₄ + 2NaCl",desc:"Barium sulfate forms as a dense white precipitate when the solutions are mixed.",obs:["precipitate formation","colour change"],t:[22,22],ph:[7,7],gas:"None",ppt:"Barium sulfate",lab:"ppt",atoms:[["Ba","Cl","Cl"],["Na","Na","S","O","O","O","O"]],groups:[[0,5,6,7,8],[3,1],[4,2]],elements:["Ba","Cl","Cl","Na","Na","S","O","O","O","O"],hint:"Two solutions form an insoluble white salt."},
propane:{name:"Propane combustion",type:"combustion",reactants:["propane","oxygen"],products:["carbon dioxide","water"],f:["C₃H₈","O₂","CO₂","H₂O"],side:["r","r","p","p"],coef:[1,5,3,4],eq:"C₃H₈ + 5O₂ → 3CO₂ + 4H₂O",desc:"Propane burns in oxygen, releasing heat and light and producing carbon dioxide and water.",obs:["light production","temperature increase","gas formation"],t:[22,250],ph:null,gas:"Carbon dioxide and water vapour",ppt:"None",lab:"flame",atoms:[["C","C","C","H","H","H","H","H","H","H","H"],["O","O"],["O","O"],["O","O"],["O","O"],["O","O"]],groups:[[11,0,12],[13,1,14],[15,2,16],[3,17,4],[5,18,6],[7,19,8],[9,20,10]],elements:["C","C","C","H","H","H","H","H","H","H","H","O","O","O","O","O","O","O","O","O","O"],hint:"A hydrocarbon reacts with oxygen and releases energy."},
ethanol:{name:"Ethanol combustion",type:"combustion",reactants:["ethanol","oxygen"],products:["carbon dioxide","water"],f:["C₂H₅OH","O₂","CO₂","H₂O"],side:["r","r","p","p"],coef:[1,3,2,3],eq:"C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O",desc:"Ethanol burns in oxygen to produce carbon dioxide and water while releasing heat and light.",obs:["light production","temperature increase","gas formation"],t:[22,210],ph:null,gas:"Carbon dioxide and water vapour",ppt:"None",lab:"flame",atoms:[["C","C","H","H","H","H","H","O","H"],["O","O"],["O","O"],["O","O"]],groups:[[9,0,10],[11,1,12],[2,7,3],[4,13,5],[6,14,8]],elements:["C","C","H","H","H","H","H","O","H","O","O","O","O","O","O"],hint:"An alcohol reacts with oxygen and releases energy."},
h2so4koh:{name:"Sulfuric acid reacting with potassium hydroxide",type:"acid–base neutralisation",reactants:["sulfuric acid","potassium hydroxide"],products:["potassium sulfate","water"],f:["H₂SO₄","KOH","K₂SO₄","H₂O"],side:["r","r","p","p"],coef:[1,2,1,2],eq:"H₂SO₄ + 2KOH → K₂SO₄ + 2H₂O",desc:"Sulfuric acid and potassium hydroxide neutralise to form potassium sulfate and water.",obs:["temperature increase","pH change"],t:[22,31],ph:[1,7],gas:"None",ppt:"None",lab:"neutral",atoms:[["H","H","S","O","O","O","O"],["K","O","H"],["K","O","H"]],groups:[[7,10,2,3,4,5,6],[0,8,9],[1,11,12]],elements:["H","H","S","O","O","O","O","K","O","H","K","O","H"],hint:"An acid and base form a salt and water."},
hclcarbonate:{name:"Hydrochloric acid reacting with calcium carbonate",type:"double displacement",reactants:["hydrochloric acid","calcium carbonate"],products:["calcium chloride","carbon dioxide","water"],f:["HCl","CaCO₃","CaCl₂","CO₂","H₂O"],side:["r","r","p","p","p"],coef:[2,1,1,1,1],eq:"2HCl + CaCO₃ → CaCl₂ + CO₂ + H₂O",desc:"Hydrochloric acid reacts with calcium carbonate. Carbon dioxide bubbles form and the solid dissolves.",obs:["gas formation","solid dissolves","temperature change"],t:[22,20],ph:[1,2],gas:"Carbon dioxide",ppt:"None",lab:"metal",atoms:[["H","Cl"],["H","Cl"],["Ca","C","O","O","O"]],groups:[[4,1,3],[5,6,7],[0,8,2]],elements:["H","Cl","H","Cl","Ca","C","O","O","O"],hint:"An acid reacts with a carbonate to form salt, water and carbon dioxide."},
cuOacid:{name:"Copper oxide reacting with sulfuric acid",type:"acid–base neutralisation",reactants:["copper oxide","sulfuric acid"],products:["copper sulfate","water"],f:["CuO","H₂SO₄","CuSO₄","H₂O"],side:["r","r","p","p"],coef:[1,1,1,1],eq:"CuO + H₂SO₄ → CuSO₄ + H₂O",desc:"Black copper oxide reacts with sulfuric acid. The solid dissolves and a blue copper sulfate solution forms.",obs:["colour change","solid dissolves","temperature increase"],t:[22,29],ph:[1,4],gas:"None",ppt:"None",lab:"metal",atoms:[["Cu","O"],["H","H","S","O","O","O","O"]],groups:[[0,4,5,6,7,8],[2,1,3]],elements:["Cu","O","H","H","S","O","O","O","O"],hint:"A basic metal oxide reacts with an acid to form salt and water."}

};
const TYPES=["synthesis","decomposition","single displacement","double displacement","combustion","acid–base neutralisation"];
const OBS=["colour change","gas formation","precipitate formation","temperature increase","temperature decrease","light production","pH change","solid dissolves","solid formation"];
const S={id:"mg",mode:"explore",p:0,run:false,last:0,speed:1,rows:[],score:0,quiz:null,quizAnswered:false,atoms:[],reactBonds:[],prodBonds:[]};
const E={};["mode","reaction","speed","scale","start","pause","step","replay","reset","theme","progress","phase","checks","record","typeAnswer","checkType","typeFeedback","builder","checkEq","eqFeedback","explanation","checkExplain","explainFeedback","dot","status","labBtn","particleBtn","splitBtn","canvasGrid","labCanvas","particleCanvas","labState","temp","ph","evidence","title","description","equation","narration","counts","csv","tbody","score","quizPrompt","quizOptions","quizFeedback","nextQuiz","modePill","librarySummary"].forEach(x=>E[x]=document.getElementById(x));
const lctx=E.labCanvas.getContext("2d"),pctx=E.particleCanvas.getContext("2d");
function R(){return DATA[S.id]}
function init(){
const grouped={};Object.entries(DATA).forEach(([k,r])=>(grouped[r.type]??=[]).push([k,r]));
E.reaction.innerHTML=Object.entries(grouped).map(([type,items])=>`<optgroup label="${cap(type)}">${items.map(([k,r])=>`<option value="${k}">${r.name}</option>`).join("")}</optgroup>`).join("");
const countsByType={};Object.values(DATA).forEach(r=>countsByType[r.type]=(countsByType[r.type]||0)+1);
E.librarySummary.innerHTML=Object.entries(countsByType).map(([type,n])=>`<div class="library-chip"><strong>${n}</strong><span>${cap(type)}</span></div>`).join("");E.checks.innerHTML=OBS.map(o=>`<label class="check"><input type="checkbox" value="${o}">${cap(o)}</label>`).join("");bind();resize();load("mg");newQuiz();requestAnimationFrame(loop)}
function bind(){addEventListener("resize",resize);E.reaction.onchange=()=>load(E.reaction.value);E.mode.onchange=()=>{S.mode=E.mode.value;applyMode();reset(false)};E.speed.onchange=()=>S.speed=+E.speed.value;E.start.onclick=()=>{if(S.p>=1)reset(false);S.run=true;status("run")};E.pause.onclick=()=>{S.run=false;status("pause")};E.step.onclick=()=>{S.run=false;S.p=Math.min(1,S.p+.035);status(S.p>=1?"done":"pause")};E.replay.onclick=()=>{reset(false);S.run=true;status("run")};E.reset.onclick=()=>reset(true);E.theme.onclick=()=>{document.body.classList.toggle("dark");E.theme.textContent=document.body.classList.contains("dark")?"Light mode":"Dark mode"};E.record.onclick=record;E.checkType.onclick=checkType;E.checkEq.onclick=checkEq;E.checkExplain.onclick=checkExplain;E.csv.onclick=csv;E.nextQuiz.onclick=newQuiz;E.labBtn.onclick=()=>view("lab");E.particleBtn.onclick=()=>view("particle");E.splitBtn.onclick=()=>view("split")}
function resize(){[E.labCanvas,E.particleCanvas].forEach(c=>{const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=Math.max(500,r.width*d);c.height=Math.max(360,r.height*d);c.getContext("2d").setTransform(d,0,0,d,0,0)})}
function load(id){S.id=id;E.reaction.value=id;buildAtoms();buildEq();reset(true);applyMode()}
function buildAtoms(){const r=R();S.atoms=[];let i=0;const W=520,H=370;const starts=[];r.atoms.forEach((g,gi)=>{const cx=(gi+1)*W/(r.atoms.length+1),cy=H*.52+(gi%2?55:-30);g.forEach((el,j)=>starts.push({x:cx+(j-(g.length-1)/2)*35,y:cy+(j%2?10:-10)}))});
const ends=Array(r.elements.length);r.groups.forEach((g,gi)=>{const cx=(gi+1)*W/(r.groups.length+1),cy=H*.52+(gi%2?50:-25);g.forEach((idx,j)=>ends[idx]={x:cx+(j-(g.length-1)/2)*35,y:cy+(j%2?9:-9)})});
r.elements.forEach((el,idx)=>S.atoms.push({id:idx,el,sx:starts[idx].x,sy:starts[idx].y,ex:ends[idx].x,ey:ends[idx].y,x:starts[idx].x,y:starts[idx].y,phase:Math.random()*6.28}));
S.reactBonds=[];let base=0;r.atoms.forEach(g=>{for(let j=0;j<g.length-1;j++)S.reactBonds.push([base+j,base+j+1]);base+=g.length});S.prodBonds=[];r.groups.forEach(g=>{for(let j=0;j<g.length-1;j++)S.prodBonds.push([g[j],g[j+1]])})}
function reset(clear){S.p=0;S.run=false;S.atoms.forEach(a=>{a.x=a.sx;a.y=a.sy});if(clear){document.querySelectorAll("#checks input").forEach(x=>x.checked=false);E.typeAnswer.value="";E.explanation.value="";fb(E.typeFeedback,"","");fb(E.eqFeedback,"","");fb(E.explainFeedback,"","")}status("pause")}
function applyMode(){const r=R();E.modePill.textContent=cap(S.mode);const hide=["mystery","challenge"].includes(S.mode);E.title.textContent=hide?"Mystery reaction":r.name;E.description.textContent=hide?"Use laboratory evidence and particle behaviour to identify the reaction.":r.desc;E.equation.textContent=["explore","guided"].includes(S.mode)?r.eq:"Build and balance the equation";E.reaction.disabled=S.mode==="mystery";if(S.mode==="mystery"){const keys=Object.keys(DATA);const k=keys[Math.floor(Math.random()*keys.length)];if(k!==S.id){S.id=k;E.reaction.value=k;buildAtoms();buildEq()}}}
function buildEq(){const r=R();E.builder.innerHTML=r.f.map((f,i)=>`<span style="display:inline-flex;align-items:center;gap:.2rem;margin:.18rem"><select data-c="${i}" style="width:54px">${[1,2,3,4,5,6].map(n=>`<option>${n}</option>`).join("")}</select><b>${fmt(f)}</b></span>${i<r.f.length-1?(r.side[i]!==r.side[i+1]?" → ":" + "):""}`).join("")}
function loop(t){const dt=Math.min(.04,(t-S.last)/1000||0);S.last=t;if(S.run){S.p=Math.min(1,S.p+dt*.22*S.speed);if(S.p>=1){S.run=false;status("done")}}updateAtoms(t);drawLab();drawParticles();updateUI();requestAnimationFrame(loop)}
function smooth(a,b,x){x=Math.max(0,Math.min(1,(x-a)/(b-a)));return x*x*(3-2*x)}
function updateAtoms(t){const move=smooth(.30,.78,S.p);S.atoms.forEach(a=>{const wig=(1-move)*5*Math.sin(t/500+a.phase);a.x=a.sx+(a.ex-a.sx)*move+wig;a.y=a.sy+(a.ey-a.sy)*move+3*Math.cos(t/420+a.phase)*(1-move)})}
function drawParticles(){const w=E.particleCanvas.clientWidth,h=E.particleCanvas.clientHeight;pctx.clearRect(0,0,w,h);const sx=w/520,sy=h/370;pctx.save();pctx.scale(sx,sy);pctx.strokeStyle="#71839a";pctx.lineWidth=5;pctx.lineCap="round";const rb=1-smooth(.18,.42,S.p),pb=smooth(.68,.9,S.p);drawBonds(S.reactBonds,rb);drawBonds(S.prodBonds,pb);S.atoms.forEach(a=>atom(a.x,a.y,a.el));pctx.restore();function drawBonds(bs,alpha){pctx.globalAlpha=alpha;bs.forEach(([i,j])=>{pctx.beginPath();pctx.moveTo(S.atoms[i].x,S.atoms[i].y);pctx.lineTo(S.atoms[j].x,S.atoms[j].y);pctx.stroke()});pctx.globalAlpha=1}function atom(x,y,el){const rad=E.scale.value==="space"?22:17;pctx.beginPath();pctx.arc(x,y,rad,0,Math.PI*2);const g=pctx.createRadialGradient(x-6,y-7,2,x,y,rad);g.addColorStop(0,"#fff");g.addColorStop(.16,C[el]||"#f97316");g.addColorStop(1,shade(C[el]||"#f97316",-35));pctx.fillStyle=g;pctx.fill();pctx.strokeStyle="rgba(0,0,0,.24)";pctx.lineWidth=1.5;pctx.stroke();pctx.fillStyle=["H","Mg","Ag"].includes(el)?"#17202b":"#fff";pctx.font="700 11px system-ui";pctx.textAlign="center";pctx.textBaseline="middle";pctx.fillText(el,x,y)}}
function drawLab(){const w=E.labCanvas.clientWidth,h=E.labCanvas.clientHeight;lctx.clearRect(0,0,w,h);const g=lctx.createLinearGradient(0,0,0,h);g.addColorStop(0,"#dff5ff");g.addColorStop(.7,"#f3fbff");g.addColorStop(.705,"#9a704e");g.addColorStop(1,"#765033");lctx.fillStyle=g;lctx.fillRect(0,0,w,h);const r=R(),p=S.p;lctx.save();lctx.translate(w/2,h*.72);if(["bubble","metal","ppt","neutral"].includes(r.lab)){beaker(r,p,w,h)}else if(r.lab==="burn"){burn(p)}else flame(p);lctx.restore()}
function beaker(r,p,w,h){lctx.strokeStyle="#617283";lctx.lineWidth=5;lctx.beginPath();lctx.moveTo(-80,-165);lctx.lineTo(-72,0);lctx.quadraticCurveTo(-68,35,-35,40);lctx.lineTo(35,40);lctx.quadraticCurveTo(68,35,72,0);lctx.lineTo(80,-165);lctx.stroke();let col=r.lab==="neutral"?mix("#ef9a9a","#9ee6bf",smooth(.45,.9,p)):r.lab==="ppt"?mix("#bce6ff","#e6e8eb",smooth(.45,.8,p)):"#bce6ff";lctx.fillStyle=col;lctx.fillRect(-69,-90,138,90);if(r.lab==="metal"){lctx.fillStyle="#5d6b79";lctx.fillRect(-18,-178,36,10);lctx.fillStyle="#8896a5";lctx.save();lctx.rotate(.04);lctx.fillRect(-7,-168,14,Math.max(40,150-85*smooth(.35,.9,p)));lctx.restore()}if(r.lab==="ppt"){lctx.fillStyle="rgba(250,250,250,.94)";lctx.fillRect(-68,5-35*smooth(.45,.9,p),136,35*smooth(.45,.9,p))}if(["bubble","metal"].includes(r.lab)&&p>.35){for(let i=0;i<18;i++){const q=(performance.now()/1200+i*.083)%1,x=-55+(i*37)%110,y=10-q*115;lctx.strokeStyle="rgba(255,255,255,.9)";lctx.lineWidth=2;lctx.beginPath();lctx.arc(x,y,3+(i%4),0,Math.PI*2);lctx.stroke()}}if(r.lab==="neutral"){lctx.fillStyle="#79889b";lctx.fillRect(100,-155,7,175);lctx.beginPath();lctx.arc(103.5,23,10,0,Math.PI*2);lctx.fill();lctx.fillStyle="#e53935";lctx.fillRect(102,-20-80*smooth(0,1,p),4,60+80*smooth(0,1,p));lctx.font="700 12px system-ui";lctx.fillStyle="#24364d";lctx.fillText("Thermometer",75,-172)}}
function burn(p){lctx.save();lctx.rotate(-.2);lctx.fillStyle=mix("#aeb7c2","#f5f5f5",smooth(.5,.8,p));lctx.fillRect(-9,-135,18,120);lctx.restore();if(p>.32){lctx.globalAlpha=Math.sin(Math.min(1,(p-.32)*4)*Math.PI)*.95;lctx.fillStyle="#fffbe5";lctx.beginPath();lctx.arc(0,-80,80,0,Math.PI*2);lctx.fill();lctx.globalAlpha=1}if(p>.65){lctx.fillStyle="#f7f7f4";for(let i=0;i<24;i++){const a=i*.62,rr=8+(i%6)*5;lctx.beginPath();lctx.arc(Math.cos(a)*rr*.8,28+Math.sin(a)*rr*.25,2+(i%3),0,Math.PI*2);lctx.fill()}}}
function flame(p){lctx.font=`${55+40*smooth(.3,.7,p)}px system-ui`;lctx.textAlign="center";lctx.fillText("🔥",0,-20);if(p>.72){lctx.fillStyle="rgba(255,255,255,.6)";for(let i=0;i<7;i++){lctx.beginPath();lctx.arc(-70+i*24,-120-i%2*18,7,0,Math.PI*2);lctx.fill()}}}
function updateUI(){const r=R(),p=S.p;E.progress.style.width=`${p*100}%`;const phases=p<.18?"Reactant particles moving":p<.42?"Effective collisions and bond stretching":p<.68?"Reactant bonds breaking; atoms rearranging":p<.9?"Product bonds forming":"Products formed; atom count unchanged";E.phase.textContent=phases;E.narration.textContent=phases+".";E.labState.textContent=p<.4?"Before reaction":p<.9?"Reaction occurring":"Products formed";E.temp.textContent=`${Math.round(r.t[0]+(r.t[1]-r.t[0])*smooth(.35,.9,p))} °C`;E.ph.textContent=r.ph?`${(r.ph[0]+(r.ph[1]-r.ph[0])*smooth(.35,.9,p)).toFixed(1)}`:"Not relevant";E.evidence.textContent=p<.38?"None yet":r.obs.map(cap).join(", ");E.counts.innerHTML=counts(r.elements)}
function counts(elements){const m={};elements.forEach(x=>m[x]=(m[x]||0)+1);return Object.entries(m).map(([k,v])=>`<span class="count-chip">${k}: ${v} before = ${v} after ✓</span>`).join("")}
function status(s){E.dot.className="dot"+(s==="run"?" run":s==="done"?" done":"");E.status.textContent=s==="run"?"Reaction in progress":s==="done"?"Reaction complete — atoms conserved":"Paused — ready to begin"}
function view(v){E.canvasGrid.className="canvas-grid"+(v==="lab"?" only-lab":v==="particle"?" only-particles":"");[E.labBtn,E.particleBtn,E.splitBtn].forEach(b=>b.classList.remove("active"));({lab:E.labBtn,particle:E.particleBtn,split:E.splitBtn})[v].classList.add("active");setTimeout(resize,30)}
function checkType(){const a=E.typeAnswer.value,r=R();if(!a)return fb(E.typeFeedback,"Choose a reaction type first.","hint");fb(E.typeFeedback,a===r.type?`Correct — this is ${r.type}.`:S.mode==="challenge"?"Not yet. Compare the reactant and product patterns.":`Not quite. Hint: ${r.hint}`,a===r.type?"good":"bad")}
function checkEq(){const a=[...document.querySelectorAll("[data-c]")].map(x=>+x.value),ok=a.every((n,i)=>n===R().coef[i]);fb(E.eqFeedback,ok?`Correct: ${R().eq}. Atom numbers match on both sides.`:"Not balanced yet. Count each element and change coefficients, not subscripts.",ok?"good":"bad")}
function checkExplain(){const x=E.explanation.value.toLowerCase(),n=[/atom/,/same|equal|conserv/,/rearrang|bond/,/reactant/,/product/].filter(q=>q.test(x)).length;fb(E.explainFeedback,x.length<25?"Add more detail using atoms, reactants and products.":n>=4?"Strong explanation: atoms persist and are rearranged into new products.":"State that atoms are not created or destroyed; existing atoms are rearranged as bonds change.",n>=4?"good":"hint")}
function record(){const r=R(),selected=[...document.querySelectorAll("#checks input:checked")].map(x=>x.value);S.rows.push({a:r.reactants.join(" + "),b:r.products.join(" + "),o:(selected.length?selected:r.obs).join("; "),t:`${r.t[0]} °C → ${r.t[1]} °C`,ph:r.ph?`${r.ph[0]} → ${r.ph[1]}`:"Not relevant",g:r.gas,p:r.ppt,c:r.type});E.tbody.innerHTML=S.rows.map(x=>`<tr><td>${x.a}</td><td>${x.b}</td><td>${x.o}</td><td>${x.t}</td><td>${x.ph}</td><td>${x.g}</td><td>${x.p}</td><td>${cap(x.c)}</td></tr>`).join("")}
function csv(){if(!S.rows.length)return alert("Record at least one reaction first.");const heads=["Reactants","Products","Observations","Temperature","pH","Gas","Precipitate","Classification"],rows=S.rows.map(x=>Object.values(x)),text=[heads,...rows].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),url=URL.createObjectURL(new Blob([text],{type:"text/csv"})),a=document.createElement("a");a.href=url;a.download="chemical-reaction-reactor-results.csv";a.click();URL.revokeObjectURL(url)}
function newQuiz(){S.quizAnswered=false;const arr=Object.values(DATA);S.quiz=arr[Math.floor(Math.random()*arr.length)];E.quizPrompt.innerHTML=`<b>${cap(S.quiz.reactants.join(" + "))} → ${cap(S.quiz.products.join(" + "))}</b><p>Evidence: ${S.quiz.obs.map(cap).join(", ")}. Classify the reaction.</p>`;let opts=shuffle(TYPES).slice(0,4);if(!opts.includes(S.quiz.type))opts[0]=S.quiz.type;opts=shuffle(opts);E.quizOptions.innerHTML=opts.map(o=>`<button data-q="${o}">${cap(o)}</button>`).join("");E.quizOptions.querySelectorAll("button").forEach(b=>b.onclick=()=>answerQuiz(b));fb(E.quizFeedback,"","")}
function answerQuiz(b){if(S.quizAnswered)return;S.quizAnswered=true;const ok=b.dataset.q===S.quiz.type;E.quizOptions.querySelectorAll("button").forEach(x=>{x.disabled=true;if(x.dataset.q===S.quiz.type)x.style.background="#d9f7e9"});if(ok)S.score++;fb(E.quizFeedback,ok?`Correct. ${S.quiz.hint}`:`The correct answer is ${S.quiz.type}. ${S.quiz.hint}`,ok?"good":"bad");E.score.textContent=`${S.score} correct`}
function fb(e,m,c){e.textContent=m;e.className="feedback"+(c?" "+c:"")}function cap(s){return s.charAt(0).toUpperCase()+s.slice(1)}function fmt(s){return s.replace(/(\d+)/g,"<sub>$1</sub>")}function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function mix(a,b,t){const A=parseInt(a.slice(1),16),B=parseInt(b.slice(1),16),ar=A>>16,ag=A>>8&255,ab=A&255,br=B>>16,bg=B>>8&255,bb=B&255;return`rgb(${Math.round(ar+(br-ar)*t)},${Math.round(ag+(bg-ag)*t)},${Math.round(ab+(bb-ab)*t)})`}
function shade(hex,amt){let n=parseInt(hex.slice(1),16),r=Math.max(0,Math.min(255,(n>>16)+amt)),g=Math.max(0,Math.min(255,(n>>8&255)+amt)),b=Math.max(0,Math.min(255,(n&255)+amt));return`rgb(${r},${g},${b})`}
init()})();
